server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.57.130:1111   #换成虚拟机中Nginx的1111端口做集群
        #server-addr: localhost:8848 #配置nacos地址


management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露服务端点
