server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment-routh #payment_route  #路由的ID,没有固定规则，但要唯一，建议配合服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址,lb即loadbalanced负载均衡
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由

        - id: payment-routh2 #payment_route  #路由的ID,没有固定规则，但要唯一，建议配合服务名
#          uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service  #匹配后提供服务的路由地址,lb即loadbalanced负载均衡
          filters:
           - AddrequestHeader=Truth,block is freaking awsome! #添加请求头过滤器 Truth=block is freaking awsome!
          predicates:
           - Path=/payment/lb/**   #匹配后提供服务的路由地址
      #           - After=2021-09-10T17:27:12.981+08:00[Asia/Shanghai] #表示某个时间点后才能访问
      #           - Between=2021-09-10T17:27:12.981+08:00[Asia/Shanghai],2021-09-10T18:27:12.981+08:00[Asia/Shanghai] #2个时间点之间
      #           -Before=2021-09-10T17:27:12.981+08:00[Asia/Shanghai] #之前
      #           - Cookie=username,wang #带cookie,key为username,value是wang，可以正则表达式
      #           - Header=X-Request-Id,\d+ #请求头含X-Request-Id的属性，值为整数的正则表达式
      #           - Host=**.block.com,**.block.org
      #           - Method= #方法
      #           - Query=username,\d+ #请求参数要带username，且值为整数的才能请求
      #

      default-filters: #spring-gateway先加载这个default-filters,再加载routes里的filters,最后加载globalFilter
        - AddrequestHeader=Truth,block is freaking awsome! #添加请求头过滤器 Truth=block is freaking awsome!

      #解决跨域问题
      globalcors:
        add-to-simple-url-handler-mapping: true #解决options请求被拦截问题
        cors-configurations: #全局的跨域处理
          '[/**]':
            allowOrigins: #允许哪些网站的跨域请求
              - "http://localhost:98090"
              - "http://www.block.org"
            allowMethods: #允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowHeaders: "*" #允许在请求中携带的头信息
            allowCredentials: true #是否允许携带Cookie
            maxAge: 360000 #这次跨域检测的有效期


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true #向注册中心注册
    fetch-registry: true #向注册中心抓取微服务信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

