server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com #eureka服务的实例名称
  client:
    register-with-eureka: false  #false表示不向注册中心注册自己
    fetch-registry: false #false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #设置与eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://eureka7002.com:7002/eureka/
#  server:
#    enable-self-preservation: false #关闭eureka自我保护机制，默认是开启的
#    eviction-interval-timer-in-ms: 2000 #设置2秒间隔心跳，默认90s