server:
  port: 80
eureka:
  client:
    register-with-eureka: false  #表示是否将自己注册进EurekaServer 默认true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

#ribbon:
#  #指的是建立连接后从服务器读取到可用资源所用的时间
#  ReadTimeout: 5000
#  #指的是建立连接所用数据，适用于网络状态正常情况下，两端连接所用的时间
#  ConnectTimeout: 5000
logging:
  level:
    #feign日志以什么级别监控哪个接口
    com.block.springcloud.service.PaymentFeignService: debug

